version: "2017-09-20"
pipeline:
  - id: build
    type: script
    overlay: ci/scala
    commands:
      - desc: Build and push docker image
        cmd: |
          sbt compile test docker:publish -Ddocker.repo=registry-write.opensource.zalan.do/machina
