version: '3.3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:1.0.0
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "internal-infos-events_v1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092

  remora:
    build: ./target/docker/stage
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_ENDPOINT=${DOCKER_IP}:9092
    hostname: remora
    ports:
      - 9000:9000