name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - name: Setup Scala
      uses: coursier/setup-action@v1
      with:
        jvm: openjdk:17
        apps: sbtn

    - name: Run tests
      run: sbt test
